### ISSUE TITLE
"Zur Kasse gehen!" Button funktioniert beim zweiten mal nicht

### ISSUE THREAD

**Issue by plusx** [shopware5/shopware#18]
Wenn man auf der letzten Seite vom Bestellprozess wieder zurück geht und erneut auf den Button "Zur Kasse gehen" klickt, funktioniert der Button nicht.

Firebug gibt mir folgende Meldung:

``` javascript
jQuery172009927556357087419_1349428699956("<h2><span class=\"frontend_error_exception\">Ups! Ein Fehler ist aufgetreten!<\/span><\/h2>\n\n\t<p>\n\t\t<span class=\"frontend_error_exception\">Die nachfolgenden Hinweise sollten Ihnen weiterhelfen.<\/span>\n\t<\/p>\n\n\t<h3>Template was not loaded failure in Enlight\/View\/Default.php on line 97<\/h3>\n\t\n\t<h3>Stack trace:<\/h3>\n\t<div style=\"overflow:auto;\">\n\t<pre>#0 Enlight\/View\/Default.php(179): Enlight_View_Default-&gt;Template()\n#1 Shopware\/Plugins\/Community\/Frontend\/SwagBackgroundImage\/Bootstrap.php(77): Enlight_View_Default-&gt;extendsTemplate(&#039;frontend\/plugin...&#039;)\n#2 Enlight\/Event\/Handler\/Plugin.php(149): Shopware_Plugins_Frontend_SwagBackgroundImage_Bootstrap-&gt;onPostDispatch(Object(Enlight_Event_EventArgs))\n#3 Enlight\/Event\/EventManager.php(156): Enlight_Event_Handler_Plugin-&gt;execute(Object(Enlight_Event_EventArgs))\n#4 Enlight\/Controller\/Action.php(147): Enlight_Event_EventManager-&gt;notify(&#039;Enlight_Control...&#039;, Array)\n#5 Enlight\/Controller\/Dispatcher\/Default.php(521): Enlight_Controller_Action-&gt;dispatch(&#039;ajaxLoginAction&#039;)\n#6 Enlight\/Controller\/Front.php(214): Enlight_Controller_Dispatcher_Default-&gt;dispatch(Object(Enlight_Controller_Request_RequestHttp), Object(Enlight_Controller_Response_ResponseHttp))\n#7 Shopware\/Bootstrap.php(79): Enlight_Controller_Front-&gt;dispatch()\n#8 Enlight\/Application.php(192): Shopware_Bootstrap-&gt;run()\n#9 shopware.php(74): Enlight_Application-&gt;run()\n#10 {main}<\/pre>\n\t<\/div>\n<div class=\"doublespace\">&nbsp;<\/div>");
```

Wenn ich das Plugin deaktiviere, funktioniert alles.
Das Problem gibt's auch, wenn andere Plugins aktiv sind. Scheint also nicht direkt an den Plugins zu liegen.

**Comment by MarcelSchmaeing** [comment]
Hi,

dieses Verhalten scheint wirklich mit dem Plugin zu tun zu haben.

Wir haben hierfür ein Ticket angelegt sodass dieses Verhalten mit der nächsten Pluginversion zeitnah erledigt sein sollte.

Viele Grüße,

Marcel

**Comment by plusx** [comment]
Hallo Marcel,

ich schreibe gerade eigene Plugins nach der Anleitung von Shopware, dort 
tritt das Verhalten auch auf.
Es wäre interessant, woran es denn liegt.

Gruß
Marco

Am 05.10.2012 11:58, schrieb tomlose:
